version: 2
builds:
  - id: "pickpocket"
    binary: pick
    ldflags:
      - -X github.com/wu-json/pickpocket/cmd.Version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - pickpocket
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 20m
checksum:
  algorithm: sha256
snapshot:
  version_template: "{{ .Version }}"
